# 1. Project Identity
spring.application.name=SmartServe

# 2. MySQL Database Connection
# This line tells Java WHERE the database is and WHAT it's named
spring.datasource.url=jdbc:mysql://localhost:3306/smartserve

# These lines provide the "Keys" to enter the database
spring.datasource.username=root
spring.datasource.password=6625#Hash

# 3. Hibernate / JPA Settings
# 'update' tells Java to create the 'food' table for you automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. Server Port
# This is the address: http://localhost:8080
server.port=8080

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ryhaan066@gmail.com
spring.mail.password=cneo oyvl axkq dhmf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true